services:
  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: "${PROJECT_NAME}-prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    ports:
      - 9090:9090
    restart: always


  grafana:
    image: grafana/grafana:12.4.0-19363970803
    container_name: "${PROJECT_NAME}-grafana"
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafana

#  loki:
#    image: grafana/loki:main-698b54l-WIP
#    container_name: "${PROJECT_NAME}-loki"
#    ports:
#      - 3100:3100

volumes:
  prom_data:
  grafana-storage:
