services:
  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: "${PROJECT_NAME}-prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    ports:
      - 9090:9090
    restart: always


  grafana:
    image: grafana/grafana:12.4.0-19363970803
    container_name: "${PROJECT_NAME}-grafana"
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafana

  loki:
    image: grafana/loki
    container_name: "${PROJECT_NAME}-loki"
    ports:
      - 3100:3100
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml

  alertmanager:
    image: prom/alertmanager
    ports:
      - 127.0.0.1:9093:9093
    container_name: alertmanager
    hostname: alertmanager
    restart: unless-stopped
    user: "0:0"
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alert_data'
      - '--cluster.listen-address='
    env_file:
      - .env
    environment:
      TZ: "Europe/Moscow"
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    volumes:
      - alertmanager-data:/alert_data
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml:ro
      - ./alertmanager/templates:/etc/alertmanager/templates:ro

volumes:
  prom_data:
  grafana-storage:
  alertmanager-data:
