global:
  resolve_timeout: 30m

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: []
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 24h
  receiver: atm-alerts

receivers:
- name: atm-alerts
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: '{{ env "TELEGRAM_BOT_TOKEN" }}'
    chat_id: '{{ env "TELEGRAM_CHAT_ID" }}'
    message: '{{ template "telegram.message" . }}'
    parse_mode: HTML
    send_resolved: true
