services:
  mysql:
    image: mysql:9.5.0
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  wordpress:
    image: wordpress:6.8.3
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wp
    ports:
      - "80:80"
    volumes:
      - ./.srv/wordpress:/var/www/html
      - ./.srv/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - mysql

  node-exporter:
    image: prom/node-exporter
    container_name: "${PROJECT_NAME}-node-exporter"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: always
    ports:
      - 9100:9100


  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: "${PROJECT_NAME}-cadvisor-exporter"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: always
    ports:
      - 8000:8080

  mysqld_exporter:
    image: prom/mysqld-exporter:v0.18.0
    container_name: mysqld-exporter
    restart: always
    command:
      - "--mysqld.username=wordpress:wordpress"
      - "--mysqld.address=mysql:3306"
    ports:
      - "9104:9104"
    depends_on:
      - mysql

volumes:
  db:
